### ISSUE TITLE
setup.py and problems with  from segstats_jsonld import mapping_data

### ISSUE THREAD

**Issue by dbkeator** [dbkeator/segstats_jsonld#19]
Hi @adswa 

Trying to run python code from terminal window.  After running setup.py and then trying to run segstats2nidm I get an error with one of your imports:  from segstats_jsonld import mapping_data.  Can you take a look?

Thanks,
Dave

[~/Documents/Coding/segstats_jsonld]$ python setup.py install
WARNING: pypandoc failed to import or threw an error while converting README.md to RST: ModuleNotFoundError("No module named 'pypandoc'")  .md version will be used as is
running install
running bdist_egg
running egg_info
writing segstats_jsonld.egg-info/PKG-INFO
writing dependency_links to segstats_jsonld.egg-info/dependency_links.txt
writing entry points to segstats_jsonld.egg-info/entry_points.txt
writing requirements to segstats_jsonld.egg-info/requires.txt
writing top-level names to segstats_jsonld.egg-info/top_level.txt
reading manifest file 'segstats_jsonld.egg-info/SOURCES.txt'
writing manifest file 'segstats_jsonld.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
copying segstats_jsonld/fs_to_nidm.py -> build/lib/segstats_jsonld
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld
copying build/lib/segstats_jsonld/fs_to_nidm.py -> build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld
creating build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/tests
copying build/lib/segstats_jsonld/tests/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/tests
copying build/lib/segstats_jsonld/tests/test_fs_to_nidm.py -> build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/tests
copying build/lib/segstats_jsonld/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld
byte-compiling build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/fs_to_nidm.py to fs_to_nidm.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/tests/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/tests/test_fs_to_nidm.py to test_fs_to_nidm.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/segstats_jsonld/__init__.py to __init__.cpython-37.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying segstats_jsonld.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying segstats_jsonld.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying segstats_jsonld.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying segstats_jsonld.egg-info/entry_points.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying segstats_jsonld.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying segstats_jsonld.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
segstats_jsonld.__pycache__.fs_to_nidm.cpython-37: module references __path__
segstats_jsonld.tests.__pycache__.test_fs_to_nidm.cpython-37: module references __path__
creating 'dist/segstats_jsonld-0.0.1-py3.7.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing segstats_jsonld-0.0.1-py3.7.egg
removing '/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg' (and everything under it)
creating /miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg
Extracting segstats_jsonld-0.0.1-py3.7.egg to /miniconda3/lib/python3.7/site-packages
segstats-jsonld 0.0.1 is already the active version in easy-install.pth
Installing segstats2nidm script to /miniconda3/bin

Installed /miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg
Processing dependencies for segstats-jsonld==0.0.1
Searching for pandas==0.24.2
Best match: pandas 0.24.2
Adding pandas 0.24.2 to easy-install.pth file

Using /miniconda3/lib/python3.7/site-packages
Searching for numpy==1.15.4
Best match: numpy 1.15.4
Adding numpy 1.15.4 to easy-install.pth file

Using /miniconda3/lib/python3.7/site-packages
Searching for pytz==2018.7
Best match: pytz 2018.7
Adding pytz 2018.7 to easy-install.pth file

Using /miniconda3/lib/python3.7/site-packages
Searching for python-dateutil==2.7.5
Best match: python-dateutil 2.7.5
Adding python-dateutil 2.7.5 to easy-install.pth file

Using /miniconda3/lib/python3.7/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /miniconda3/lib/python3.7/site-packages
Finished processing dependencies for segstats-jsonld==0.0.1

[~]$ segstats2nidm 
Traceback (most recent call last):
  File "/miniconda3/bin/segstats2nidm", line 11, in <module>
    load_entry_point('segstats-jsonld==0.0.1', 'console_scripts', 'segstats2nidm')()
  File "/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg/segstats_jsonld/__init__.py", line 14, in <module>
    from .fs_to_nidm import (remap2json,
  File "/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg/segstats_jsonld/fs_to_nidm.py", line 63, in <module>
    from segstats_jsonld import mapping_data
ImportError: cannot import name 'mapping_data' from 'segstats_jsonld' (/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg/segstats_jsonld/__init__.py)

**Comment by dbkeator** [comment]
Seems like I fixed this in [commit](https://github.com/dbkeator/segstats_jsonld/commit/bfe12c7388e61b65bd0e6f0cb61c6a4d6897f06a)
