### ISSUE TITLE
setup.py not copying XLS file 

### ISSUE THREAD

**Issue by dbkeator** [dbkeator/segstats_jsonld#20]
Hi @adswa ,

After installing package with python setup.py install, I find that the script can't be run without supplying a the jsonmap.json file with the command line parameter -jmap because the ReproNimCDEs.xlsx file in mapping_data isn't copied into the site_packages directory (see below).  Any ideas?

[~/Documents/Coding/segstats_jsonld]$ segstats2nidm -f "https://fcp-indi.s3.amazonaws.com/data/Projects/ABIDE/Outputs/mindboggle_swf/mindboggle/freesurfer_subjects/sub-0050190/stats/aseg.stats" -subjid 0050190 -n /Users/dbkeator/Documents/Coding/simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/SDSU/nidm.ttl -o /Users/dbkeator/Documents/Coding/simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/SDSU/nidm.ttl
Traceback (most recent call last):
  File "/miniconda3/bin/segstats2nidm", line 11, in <module>
    load_entry_point('segstats-jsonld==0.0.1', 'console_scripts', 'segstats2nidm')()
  File "/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg/segstats_jsonld/fs_to_nidm.py", line 916, in main
    fs_stat_file=stats_file)
  File "/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg/segstats_jsonld/fs_to_nidm.py", line 458, in remap2json
    xls = pd.ExcelFile(xlsxfile)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/excel.py", line 653, in __init__
    self._reader = self._engines[engine](self._io)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/excel.py", line 424, in __init__
    self.book = xlrd.open_workbook(filepath_or_buffer)
  File "/miniconda3/lib/python3.7/site-packages/xlrd/__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/miniconda3/lib/python3.7/site-packages/segstats_jsonld-0.0.1-py3.7.egg/segstats_jsonld/mapping_data/ReproNimCDEs.xlsx'

**Comment by adswa** [comment]
will finally look into this today, sorry for the delay.

**Comment by adswa** [comment]
I'm for now including the xlxs file in the distribution. You should be able to pip uninstall segstats_jsonld and subsequently install the fresh release with pip install -i https://test.pypi.org/simple/ segstats-jsonld.

Please let me know whether this fixes it, @dbkeator
