### ISSUE TITLE
remap2json problem with aparcs

### ISSUE THREAD

**Issue by dbkeator** [dbkeator/segstats_jsonld#4]
Traceback (most recent call last):
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/dbkeator/Documents/Coding/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 652, in <module>
    main(sys.argv[1:])
  File "/Users/dbkeator/Documents/Coding/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 622, in main
    fs_stat_file=os.path.join(args.subject_dir,"stats",stats_file))
  File "/Users/dbkeator/Documents/Coding/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 447, in remap2json
    if row['Structure - Assuming Cortical Areas (not sulci)']['Label'] is not np.nan else ""
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3132, in get_value
    raise e1
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Label'

Process finished with exit code 1

**Comment by adswa** [comment]
can't reproduce the above error, however, could you pull (updated to xlsx file), try to rerun, and post the full traceback? thx!
